### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by camilamacedo86**

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@darahayes and @aliok could you please check this one?

**Comment by camilamacedo86** [comment]
@wtrocki more +1

**Comment by aliok** [comment]
Nothing to check on this one. It is a standard Apache License template file. Feel free to merge

**Comment by camilamacedo86** [comment]
@aliok could you give me the permission to do it? I am not allowed :-(

**Pull request merged**
